# Generated by Django 4.2.1 on 2023-05-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pomodorocalendar", "0002_remove_task_session_sessiontaskcontainer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
