# Generated by Django 4.2.1 on 2023-05-24 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pomodorocalendar", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="session",
        ),
        migrations.CreateModel(
            name="SessionTaskContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pomodorocalendar.session",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pomodorocalendar.task",
                    ),
                ),
            ],
        ),
    ]
